print("----QUIZ GAME----")
print("Here the questions")
questions=[
    {
        "question":"Which symbol is used to create a list in Python?",
        "option":["1. ()","2. []","3. {}","4. <>"],
        "answer":2
    },

    {
        "question":"Which function is used to take input from the user in Python?",
        "option":["1. print()","2. input()","3. scan()","4. get()"],
        "answer":2
    },

    {
        "question":"What is the output of 10 % 3?",
        "option":["1","2","3","0"],
        "answer":1
    },

    {
        "question":"Which keyword is used to define a function in Python?",
        "option":["1. function","2. fun" ,"3. def","4. define"],
        "answer":3
    },

    {
        "question":"What values are generated by range(5)?",
        "option":["1,2,3,4,5","0,1,2,3,4","0,1,2,3,4,5","5"],
        "answer":2
    },
]

score=0
for q in questions:
    print(q["question"])
    print(q["option"])
    user=int(input("choose the option: "))
    if user==(q["answer"]):
        print("wow!, Your is correct")
        score+=1
    else:
        print("Your answer is incorrect")
        print("Correct answer is",q["answer"])
print("Your score is" ,score)
print("----END QUIZZ----")